server.port=8082

spring.application.name=customer-service

spring.config.import=classpath:application-common.properties

spring.datasource.url=${CUSTOMER_DB_URL:jdbc:postgresql://localhost:5432/customerdb}
