server.port=8084

spring.application.name=order-service

spring.config.import=classpath:application-common.properties

spring.datasource.url=jdbc:postgresql://localhost:5432/orderdb

clients.customer-service.url=http://localhost:8082
clients.product-service.url=http://localhost:8083
