server.port=8084

spring.application.name=order-service

spring.config.import=classpath:application-common.properties

spring.datasource.url=${ORDER_DB_URL:jdbc:postgresql://localhost:5432/orderdb}

clients.customer-service.url=${CUSTOMER_SERVICE_URL:http://localhost:8082}
clients.product-service.url=${PRODUCT_SERVICE_URL:http://localhost:8083}
clients.connect-timeout-ms=${CLIENT_CONNECT_TIMEOUT_MS:3000}
clients.read-timeout-ms=${CLIENT_READ_TIMEOUT_MS:5000}
